Repository slohacks/club, pull requests merged in 2018-05, with the labels that each got.

#26 fix(NavBar.jsx, NavItem.jsx): revert pr #21 due to lint errors
  src/components/NavBar.jsx
  src/components/NavBar.module.css
  src/components/NavItem.jsx
  src/components/NavItem.module.css
  src/pages/index.jsx
  src/tests/components/NavBar.test.jsx
Labels: bug

#28 fix(pages, components, package.json): correct various aspects of website
  package.json
  src/components/Button.module.css
  src/pages/index.jsx
Labels: fix

#29 fix(pages/index): change event names from `h3` to `h4`
  src/pages/index.jsx
Labels: fix

#36 feat(layouts/index): add smooth scroll polyfill
  package.json
  src/layouts/index.jsx
  yarn.lock
Labels: feat

#37 feat(assets, pages/index): add team photo window
  src/assets/teamColor.jpg
  src/assets/teamWhite2.jpg
  src/pages/index.jsx
  src/pages/index.module.css
Labels: feat, refactor

#38 feat(pages/index): add gutter for content
  src/pages/index.jsx
  src/pages/index.module.css
Labels: feat

#41 ci(.travis.yml): replace lint script with actual commands
  .travis.yml
Labels: chore, fix

#42 style(pages/index): add space
  src/pages/index.jsx
Labels: style

#40 feat(pages/index, assets): add partner logos
  src/assets/partners__brandmakers.png
  src/assets/partners__oldslo.png
  src/pages/index.jsx
  src/pages/index.module.css
Labels: feat

#43 revert(pages/index, assets): undo faulty changes
  src/assets/partners__brandmakers.png
  src/assets/partners__oldslo.png
  src/pages/index.jsx
  src/pages/index.module.css
Labels: fix

#34 feat(NavBar.jsx, NavItem.jsx): add NavBar component
  package.json
  src/components/NavBar.jsx
  src/components/NavBar.module.css
  src/components/NavItem.jsx
  src/components/NavItem.module.css
  src/pages/index.jsx
  src/pages/index.module.css
  yarn.lock
Labels: feat

#19 docs(CONTRIBUTING): fix "gatsbi-cli" typo
  CONTRIBUTING.md
Labels: docs

#48 feat(pages/index, assets): add partner logos
  src/assets/partners__brandmakers.png
  src/assets/partners__oldslo.png
  src/pages/index.jsx
  src/pages/index.module.css
Labels: feat

#17 feat(pages/index): draft of subscribe section
  .travis.yml
  package-lock.json
  package.json
  src/components/Button.jsx
  src/components/Button.module.css
  src/components/ContactForm.jsx
  src/components/ContactForm.module.css
  src/pages/index.jsx
  src/pages/index.module.css
  yarn.lock
Labels: feat

#49 fix(pages/index, components/ContactForm): various fixes
  src/components/ContactForm.jsx
  src/components/NavBar.jsx
  src/components/NavBar.module.css
  src/pages/index.jsx
Labels: fix, refactor
